export const GET_BREEDS = 'GET_BREEDS';
export const GET_BREED = 'GET_BREED';
export const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS';
export const GET_FILTER_TEMPERAMENTS = 'GET_FILTER_TEMPERAMENTS'; 
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const ORDER_BY_WEIGHT = 'ORDER_BY_WEIGHT';
